// Looks up the real crest of every dam in the catalogue (src/lib/dams.ts) in OpenStreetMap and
// writes src/lib/damCrests.ts, so catalogue dams are placed exactly, without a live query.
// Dams whose lookup fails keep the line they already had.
//   node scripts/catalog-crests.ts                # query Overpass
//   node scripts/catalog-crests.ts --from <dir>   # use saved Overpass responses, <dir>/<id>.json

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DAM_CATALOG } from '../src/lib/dams.ts';
import { DAM_CRESTS } from '../src/lib/damCrests.ts';
import { fetchDamLine } from '../src/lib/osm.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const fromIndex = process.argv.indexOf('--from');
const from = fromIndex >= 0 ? process.argv[fromIndex + 1] : null;

const lengthOf = (line: [number, number][]) => {
  const k = 111_320 * Math.cos((line[0][1] * Math.PI) / 180);
  let m = 0;
  for (let i = 1; i < line.length; i++) m += Math.hypot((line[i][0] - line[i - 1][0]) * k, (line[i][1] - line[i - 1][1]) * 110_574);
  return Math.round(m);
};

const crests: Record<string, [number, number][]> = { ...DAM_CRESTS };
for (const dam of DAM_CATALOG) {
  try {
    const fetchImpl = from
      ? ((async () => new Response(await readFile(path.join(from, `${dam.id}.json`), 'utf8'))) as unknown as typeof fetch)
      : fetch;
    const line = await fetchDamLine(dam.lng, dam.lat, dam.crestLength, fetchImpl, undefined, 8000);
    if (line) {
      crests[dam.id] = line;
      console.log(`${dam.id}: ${line.length} points, ${lengthOf(line)} m (catalogue crest ${dam.crestLength} m)`);
    } else {
      console.log(`${dam.id}: no dam mapped nearby${crests[dam.id] ? ' (kept the existing line)' : ''}`);
    }
  } catch (err) {
    console.log(`${dam.id}: lookup failed (${err instanceof Error ? err.message : err})${crests[dam.id] ? '; kept the existing line' : ''}`);
  }
}

const entries = Object.entries(crests)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, line]) => `  '${id}': ${JSON.stringify(line)},`);
await writeFile(
  path.join(root, 'src', 'lib', 'damCrests.ts'),
  `// Generated by scripts/catalog-crests.ts from OpenStreetMap (© OpenStreetMap contributors, ODbL).
// The real crest of each catalogue dam, abutment to abutment, as [lng, lat].

export const DAM_CRESTS: Record<string, [number, number][]> = {
${entries.join('\n')}
};
`,
);
console.log(`\n${entries.length} of ${DAM_CATALOG.length} catalogue dams have a crest line.`);
